### ISSUE TITLE
Mac Compatibility.

### ISSUE THREAD

**Issue by j-dogcoder** [SaptakBhoumik/J.A.R.V.I.S#3]
I think this is a super cool project. Is there any way to make this Mac compatible?

**Comment by SaptakBhoumik** [comment]
Yes I am working on it so a mac and Linux compatible version will be out soon @j-dogcoder

**Comment by j-dogcoder** [comment]
Awesome! I am checking out the code now to see if there is anything I can contribute.

**Comment by SaptakBhoumik** [comment]
@j-dogcoder i dont have a mac so can you test some features for mac. if yes contact me

**Comment by j-dogcoder** [comment]
Sure! I would love to help test @SaptakBhoumik

**Comment by SaptakBhoumik** [comment]
ok contact me via email saptakbhoumik@gmail.com

**Comment by j-dogcoder** [comment]
@SaptakBhoumik I sent you an email.

**Comment by SaptakBhoumik** [comment]
@j-dogcoder I am sorry but I no longer maintain this project. Please check out my latest project https://github.com/Swallow-lang/swallow

**Comment by j-dogcoder** [comment]
@SaptakBhoumik I'll take it if you want.

**Comment by SaptakBhoumik** [comment]
@j-dogcoder Do you want to continue it?

**Comment by SaptakBhoumik** [comment]
@j-dogcoder check your mail once

**Comment by j-dogcoder** [comment]
I'd love too!

**Comment by j-dogcoder** [comment]
Want to transfer the project to me?

**Comment by SaptakBhoumik** [comment]
yes
